Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('product_app.urls',namespace='product')),
    path('martor/', include('martor.urls')),     
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product_app/urls.py
from django.urls import include , path
from product_app import views

app_name='product_app'

urlpatterns = [
    path('', views.ProductsView, name='products'),
    path('create', views.ProductsCreate.as_view(), name='create_products'),
    path('<str:slug>/product_likes/', views.Product_likes, name='product_likes'),
    path('<str:slug>', views.ProductDetailsView, name='product_details'),
    #path('<str:slug>', views.DestinationDetailsView, name='destination_details'),  #must be the last path in the list
                                                                                   #in case i have an url matchs with slug the browser will go to the url not the slug
    

]

product_app/models.py

from django.db import models
from django.db.models.enums import Choices
from django.utils.text import slugify
from django.contrib.auth.models import User
from martor.models import MartorField

categories = [
    ("Mens_products", "Men's Products"),
    ("Womens_products","Women's Products"),
    ("Accessories", "Accessories"),
    ("Home_products","Home Products"),
          ]

tags = [("New", "New"), ("Sale", "Sale"), ("Discount", "Discount")]

class Product(models.Model) :
    title = models.CharField(max_length=30,)
    author= models.ForeignKey(User, on_delete=models.CASCADE, null=False, default=1)
    published_at= models.DateTimeField(auto_now=True)
    product_cover= models.ImageField(upload_to='media/Products')
    
    price=models.IntegerField(null=False)
    discount=models.IntegerField(blank=True, null=True)
    ratings=models.IntegerField(blank=True, null=True)
    
    short_description = models.TextField(max_length=50)
    likes= models.ManyToManyField(User, blank=True, related_name="likes")
    category = models.CharField(max_length=30, choices=categories, default='Others')
    tag =  models.CharField(max_length=30, choices=tags, null=True, blank=True)
    
    slug= models.SlugField(blank=True, null=True, unique=True)
    content = models.TextField(max_length=500)
    
    
    def save(self,*args, **kwargs):              #overriding save method in admin page
        self.slug= slugify(self.title)           #create a slug
        super(Product,self).save(*args,**kwargs)


    def __str__(self):
         return self.title
    
    
class ProductGallary(models.Model):     # to show destination photos in details # check out admin.py
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to = 'media/Product_gallary')
    

    def __str__(self):
         return '{0}'.format(self.images)

product_app/forms.py
from django import forms
from .models import Product
from martor.fields import MartorFormField


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title','short_description','price','discount','product_cover','content')
        content = MartorFormField()
       

    # categories = forms.ModelMultipleChoiceField(
    #     queryset=Category.objects.all(),            # give many to many field user friendly shape
    #     widget=forms.CheckboxSelectMultiple
    # )

    




product_app/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.urls.base import reverse
from product_app.models import Product, ProductGallary
from product_app.forms import ProductForm
from django.views.generic.list import ListView
from django.views.generic import CreateView

'''
class ProductsView(ListView):
    model = Product
    queryset = Product.objects.all()
    template_name = 'product_temp/products.html'
    context_object_name ='products' 
    paginate_by = 6
'''

def ProductsView(request):
    all = Product.objects.all().order_by('price')
    
    context ={
        'all_products' :all,

        }
    return render(request, 'product_temp/products.html',context)

    
    
def ProductDetailsView(request, slug):
    product_details=Product.objects.get(slug=slug)
    product_gallery=ProductGallary.objects.filter(product=product_details)
    
    context ={
        'product_details' :product_details,
        'product_gallery' :product_gallery,

        }
    return render(request, 'product_temp/product_details.html',context)
 
 

@login_required
def Product_likes(request,slug):
    product = Product.objects.get(slug=slug)

    if request.user in product.likes.all():               # unlike or like depending if the user liked or not
        product.likes.remove(request.user)
        
        return redirect(reverse('product:product_details', args=(slug,)))
    else:
        product.likes.add(request.user)

        return redirect(reverse('product:product_details', args=(slug,))) 
 
 
 
class ProductsCreate(CreateView):
    model = Product
    template_name = 'product_temp/product_create.html'
    #context_object_name ='create_product_form'
    #fields = ('title','short_description','product_cover','content') 
    form_class = ProductForm
    success_url = ''

product_app/templates/Change of Plans/product_temp/product_create.html
{% extends "base.html" %}
{%load static%}
{% load bootstrap4 %}
{%block body%}


<section class="ftco-section ftco-no-pt ftco-no-pb">
    <div class="comment-form-wrap pt-5 ">
        <h1 class="mb-5 offset-1">Sell Product</h1>
        {{create_product_form.media}}                           <!-- ← ↓ these two to give the content its real shape  -->
        <form action="" method="POST" class="p-5 bg-light" enctype="multipart/form-data">
    <div class="form-group">
            
            {% csrf_token %}
            {% bootstrap_form form %}
            
          </div>
          <div class="form-group">
            <input type="submit" value="Create" class="btn py-3 px-4 btn-primary">
          </div>
        </section>

{% endblock %}

product_app/templates/Change of Plans/product_temp/product_details.html
{%extends "base.html"%}
{%load static%}
{%block body%}

            <div class="layout_padding-2">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                            <div class="img_box">
                                <figure><img src="icon/p2.png" alt="#" /></figure>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 product_detail_side">
                            <div class="abotext_box">
                                <div class="product-heading">
                                    <h2>Jane Lauren Design Chair</h2>
                                </div>
                                <div class="product-detail-side">
                                    <span><del>$679.89</del></span><span class="new-price">$547.60</span>
                                    <span class="rating">
                     <i class="fa fa-star" aria-hidden="true"></i>
                     <i class="fa fa-star" aria-hidden="true"></i>
                     <i class="fa fa-star" aria-hidden="true"></i>
                     <i class="fa fa-star" aria-hidden="true"></i>
                     <i class="fa fa-star-o" aria-hidden="true"></i>
                     </span>
                                    <span class="review">(5 customer review)</span>
                                </div>
                                <div class="detail-contant">
                                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
                                        <br><span class="stock">2 in stock</span>
                                    </p>
                                    <form class="cart" method="post" action="shop-cart.html">
                                        <div class="quantity">
                                            <input step="1" min="1" max="5" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" type="number">
                                        </div>
                                        <button type="submit" class="bt_main">Add to cart</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="full">
                                <div class="tab_bar_section">
                                    <ul class="nav nav-tabs" role="tablist">
                                        <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#description">Description</a> </li>
                                        <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#reviews">Reviews (2)</a> </li>
                                    </ul>
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div id="description" class="tab-pane active">
                                            <div class="product_desc">
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac elementum elit. Morbi eu arcu ipsum. Aliquam lobortis accumsan quam ac convallis. Fusce elit mauris, aliquet at odio vel, convallis vehicula nisi. Morbi vitae porttitor dolor. Integer eget metus sem. Nam venenatis mauris vel leo pulvinar, id rutrum dui varius. Nunc ac varius quam, non convallis magna. Donec suscipit commodo dapibus.
                                                    <br>
                                                    <br>Vestibulum et ullamcorper ligula. Morbi bibendum tempor rutrum. Pelle tesque auctor purus id molestie ornare.Donec eu lobortis risus. Pellentesque sed aliquam lorem. Praesent pulvinar lorem vel mauris ultrices posuere. Phasellus elit ex, gravida a semper ut, venenatis vitae diam. Nullam eget leo massa. Aenean eu consequat arcu, vitae scelerisque quam. Suspendisse risus turpis, pharetra a finibus vitae, lobortis et mi.</p>
                                            </div>
                                        </div>
                                        <div id="reviews" class="tab-pane fade">
                                            <div class="product_review">
                                                <h3>Reviews (2)</h3>
                                                <div class="commant-text row">
                                                    <div class="col-lg-2 col-md-2 col-sm-4">
                                                        <div class="profile">
                                                            <img class="img-responsive" src="images/lllll.png" alt="#">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-10 col-md-10 col-sm-8">
                                                        <h5>Ravi</h5>
                                                        <p><span class="c_date">July 23, 2019</span> | <span><a rel="nofollow" class="comment-reply-link" href="#">Reply</a></span></p>
                                                        <span class="rating">
                                 <i class="fa fa-star" aria-hidden="true"></i>
                                 <i class="fa fa-star" aria-hidden="true"></i>
                                 <i class="fa fa-star" aria-hidden="true"></i>
                                 <i class="fa fa-star" aria-hidden="true"></i>
                                 <i class="fa fa-star-o" aria-hidden="true"></i>
                                 </span>
                                                        <p class="msg">ThisThis book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, “Lorem ipsum dolor sit amet..
                                                        </p>
                                                    </div>
                                                </div>
                                                <div class="commant-text row">
                                                    <div class="col-lg-2 col-md-2 col-sm-4">
                                                        <div class="profile">
                                                            <img class="img-responsive" src="images/lllll.png" alt="#">
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-10 col-md-10 col-sm-8">
                                                        <h5>Ravi</h5>
                                                        <p><span class="c_date">July 23, 2019</span> | <span><a rel="nofollow" class="comment-reply-link" href="#">Reply</a></span></p>
                                                        <span class="rating">
                                 <i class="fa fa-star" aria-hidden="true"></i>
                                 <i class="fa fa-star" aria-hidden="true"></i>
                                 <i class="fa fa-star" aria-hidden="true"></i>
                                 <i class="fa fa-star" aria-hidden="true"></i>
                                 <i class="fa fa-star-o" aria-hidden="true"></i>
                                 </span>
                                                        <p class="msg">Nunc augue purus, posuere in accumsan sodales ac, euismod at est. Nunc faccumsan ermentum consectetur metus placerat mattis. Praesent mollis justo felis, accumsan faucibus mi maximus et. Nam hendrerit mauris id scelerisque placerat. Nam vitae imperdiet turpis</p>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        <div class="full review_bt_section">
                                                            <div class="float-right">

                                                                <a class="bt_main" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Leave a Review</a>

                                                            </div>
                                                        </div>

                                                        <div class="full">

                                                            <div id="collapseExample" class="full collapse commant_box">
                                                                <form accept-charset="UTF-8" action="index.html" method="post">
                                                                    <input id="ratings-hidden" name="rating" type="hidden">
                                                                    <textarea class="form-control animated" cols="50" id="new-review" name="comment" placeholder="Enter your review here..." required=""></textarea>
                                                                    <div class="full_bt center">
                                                                        <button class="bt_main" type="submit">Save</button>
                                                                    </div>
                                                                </form>
                                                            </div>

                                                        </div>

                                                    </div>

                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            
{%endblock body%}

product_app/templates/Change of Plans/product_temp/products.html
{%extends "base.html"%}
{%load static%}
{%block body%}

      <div class="contactus">
   <div class="container-fluid">
            <div class="row">
               <div class="col-md-8 offset-md-2">
                  <div class="title">
                     <h2>Our Products</h2>
                    
                  </div>
               </div>
            </div>
          </div>
</div>
<div class="ourproduct">
  <div class="container">
     <div class="row product_style_3" >
      <!-- product -->
      {% for product in products %}
      <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
        <div class="full product">
          <div class="product_img">
            <div class="center"> <img src={{  product.product_cover.url  }} alt="#"/>
              <div class="overlay_hover"> <a class="add-bt" href="{% static 'product_details.html' %}">+ Add to cart</a> </div>
            </div>
          </div>
          <div class="product_detail text_align_center">
            <p class="product_price">${{  product.price  }}
            {% if  product.discount != none%}
            <p span class="old_price">${{product.discount}}</span></p>
            {% endif %}
            <p class="product_descr">{{  product.short_description  }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
      <!-- end product -->
    </div>
  </div>
</div>

{%endblock body%}

product_app/templates/product_temp/product_details.html
{% extends 'n2_base.html' %}
{% load static %}
{% block body %}
  

<div class="page-banner-area">
<div class="container">
<div class="page-banner-content d-flex justify-content-between">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="index.html"><i class="lni lni-home"></i> Home</a></li>
<li class="breadcrumb-item active" aria-current="page">Product Details</li>
</ol>
<h6 class="banner-title">Product Details</h6>
</div> 
</div> 
</div>


    

<section class="product-details-area pt-30 pb-80">
<div class="container">
<div class="row justify-content-center">
<div class="col-lg-5 col-md-8 col-sm-8">
<div class="product-details-image mt-50">
<div class="details-image">
{% for image in product_gallery %}
<div class="single-product-image">
<img src="{{image.images.url}}" alt="product">
</div> 
{% endfor %}
</div> 

<ul class="product-thumbs">
{% for image in product_gallery %}
<li>
<div class="single-thumbs">
<img src="{{image.images.url}}" alt="thumbs">
</div> 
</li>
{% endfor %}

</ul> 
</div> 
</div>
<div class="col-lg-7">
<div class="product-details-content mt-45">
<h3 class="details-title">{{product_details.title}}</h3>
<div class="details-price-rating d-sm-flex justify-content-between align-items-center">
<div class="price">

{% if product_details.discount %}
<span class="price-text">${{product_details.price}} <del>${{product_details.discount}}</del></span>
{% else %}
<span class="price-text">${{product_details.price}}</span>
{% endif %}
</div>
<div class="rating d-flex">
<ul>
<li><i class="lni lni-star"></i></li>
<li><i class="lni lni-star"></i></li>
<li><i class="lni lni-star"></i></li>
<li><i class="lni lni-star"></i></li>
<li><i class="lni lni-star"></i></li>
</ul>
<span class="rating-text">(01 Customer Review)</span>
</div>
</div> 
<div class="details-overview">
<div class="details-sub-title">
<h4 class="sub-title">Quick Overview</h4>
</div>
<p class="text"> {{product_details.short_description}} </p>
</div> 

 
<div class="details-cart d-sm-flex align-items-center">
<div class="product-quantity d-flex mt-10 mr-20" id="quantity">
<button type="button" id="sub" class="sub">-</button>
<input type="text" id="1" value="0" />
<button type="button" id="add" class="add">+</button>
</div>
<div class="cart=btn mt-10">
<a class="main-btn" href="#"><i class="lni lni-cart-full"></i> Add to Cart</a>
</div>
</div> 
<div class="details-usefull">
<ul class="usefull-link">
<li><a href="#"><i class="lni lni-envelope"></i>Email to a Friend</a></li>
{% if request.user in product_details.likes.all %}
<li><a href="{% url 'product:product_likes' product_details.slug %}"><i class="lni lni-heart-filled"></i>Unlike</a></li>
{% else %}
<li><a href="{% url 'product:product_likes' product_details.slug %}"><i class="lni lni-heart"></i>Wishlist</a></li>
{% endif %}
</ul>
</div> 
<div class="details-share d-flex align-items-center">
<span class="share">Share:</span>
<ul class="social">
<li><a href="#"><i class="lni lni-facebook-filled"></i></a></li>
<li><a href="#"><i class="lni lni-twitter-filled"></i></a></li>
<li><a href="#"><i class="lni lni-instagram-original"></i></a></li>
<li><a href="#"><i class="lni lni-pinterest"></i></a></li>
</ul>
</div> 
</div> 
</div>
</div> 
</div> 
</section>


<section class="product-tab-area pt-80 pb-80">
<div class="container">
<div class="row">
<div class="col-lg-12">
<div class="product-tab">
<div class="product-tab-menu">
<ul class="nav" id="myTab" role="tablist">
<li class="nav-item">
<a class="active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">Description</a>
</li>
<li class="nav-item">
<a id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="reviews" aria-selected="false">Reviews</a>
</li>

</ul>
</div> 
<div class="product-tab-content">
<div class="tab-content" id="myTabContent">
<div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
<div class="single-tab-content description-tabs">
<h3 class="tab-title">{{product_details.title}}</h3>
<p class="text">{{product_details.content}}</p>
</div> 
</div>
<div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
<div class="single-tab-content reviews-tabs">
<div class="customer-review">
<div class="review-title pb-10">
<h4 class="title">CUSTOMER REVIEW</h4>
</div>
<ul class="product-comments">
<li>
<div class="single-review d-sm-flex">
<div class="review-author">
<img src="assets/images/review-1.jpg" alt="Author">
</div>
<div class="review-content media-body">
<h6 class="author-name">Gerald Barnes</h6>
<span class="date">27 Jun, 2016 at 2:30pm</span>
<p class="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer accumsan egestas elese ifend. Phasellus a felis at est bibendum feugiat ut eget eni Praesent et messages in con sectetur posuere dolor non.</p>
<div class="comment-reply">
<ul>
<li><a href="#"><i class="lni lni-reply"></i></a></li>
<li><a href="#"><i class="lni lni-close"></i></a></li>
</ul>
</div>
</div>
</div>
</li>
<li>
<div class="single-review d-sm-flex">
<div class="review-author">
<img src="assets/images/review-2.jpg" alt="Author">
</div>
<div class="review-content media-body">
<h6 class="author-name">Gerald Barnes</h6>
<span class="date">27 Jun, 2016 at 2:30pm</span>
<p class="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer accumsan egestas elese ifend. Phasellus a felis at est bibendum feugiat ut eget eni Praesent et messages in con sectetur posuere dolor non.</p>
<div class="comment-reply">
<ul>
<li><a href="#"><i class="lni lni-reply"></i></a></li>
<li><a href="#"><i class="lni lni-close"></i></a></li>
</ul>
</div>
</div>
</div>
</li>
</ul>
</div> 
<div class="review-form mt-30">
<div class="review-title">
<h4 class="title">LEAVE YOUR REVIW</h4>
</div>
<form action="#">
<div class="single-form">
<div class="your-rating">
<p class="text">Your Rating</p>
<span>
<a href="#"><i class="lni lni-star"></i></a>
</span>
<span class="separator">|</span>
<span>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
</span>
<span class="separator">|</span>
<span>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
</span>
<span class="separator">|</span>
<span>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
</span>
<span class="separator">|</span>
<span>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
<a href="#"><i class="lni lni-star"></i></a>
 </span>
</div>
</div>
<div class="row">
<div class="col-md-6">
<div class="single-form">
<input type="text" placeholder="Your name here...">
</div>
</div>
<div class="col-md-6">
<div class="single-form">
<input type="text" placeholder="Your name here...">
</div>
</div>
<div class="col-md-12">
<div class="single-form">
<textarea placeholder="Your review here..."></textarea>
</div>
</div>
<div class="col-md-12">
<div class="single-form">
<button class="main-btn">Submit Review</button>
</div>
</div>
</div>
</form>
</div>
</div> 
</div>

</div>
</div>
</div> 
</div> 
</div>
</div> 
</div> 
</section>

{% endblock body %}

product_app/templates/product_temp/products.html
{%extends "n2_base.html"%}
{%load static%}
{%block body%}



<div class="page-banner-area">
<div class="container">
<div class="page-banner-content d-flex justify-content-between">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="index.html"><i class="lni lni-home"></i> Home</a></li>
<li class="breadcrumb-item active" aria-current="page">Shop</li>
</ol>
<h6 class="banner-title">Shop</h6>
</div> 
</div> 
</div>


<section class="category-page pt-40 pb-80">
<div class="container">
<div class="row">
<div class="col-lg-12">
<div class="product-filter d-sm-flex justify-content-between align-items-center">
<div class="filter pt-10">
<p class="text">Showing result of your search keyword "Dress"</p>
</div>
<div class="filter pt-10 d-flex align-items-center">
<span class="sort">Sort by:</span>
<select>
<option value="0">Default sortion</option>
<option value="1">popularity</option>
<option value="2">Average ration</option>
<option value="3">newness</option>
<option value="4">price</option>
</select>
</div>
</div>
</div>
</div> 

<div class="row">
{% for product in all_products %}  
<div class="col-lg-3 col-md-6">
<div class="product-card text-center mt-30">
<div class="product-image">
<img src={{  product.product_cover.url  }} alt="product">
{% if product.tag == "New" %}
<div class="sticker new"><span>NEW</span></div>
{% elif product.tag == "Discount"%}  
<div class="sticker discount"><span>HOT</span></div>
{% elif product.tag == "Sale"%}
<div class="sticker sale"><span>SALE</span></div>
{% endif %}

</div>

<div class="product-content">
<h5 class="product-name"><a href="product-details.html">{{product.title}}</a></h5>
{% if product.discount%}
<span class="price">${{product.price}}<del>${{product.discount}}</del></span>
{% else %}
<span class="price">${{product.price}}</span>
{% endif %}
<ul class="actions">
<li><a href="#" data-toggle="modal" data-target="#exampleModalCenter"><i class="lni lni-eye"></i></a></li>
<li><a href="#"><i class="lni lni-heart"></i></a></li>
<li><a href="#"><i class="lni lni-shuffle"></i></a></li>
</ul>
</div>
</div> 
</div>
{%endfor%}
</div>

</section>



{%endblock%}

product_app/templates/product_temp/search.html
{%extends "n_base.html"%}
{%load static%}
{%block body%}

<div class="page-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">            
          <div class="breadcrumb">
            <a href="#"><i class="icon-home"></i> Home</a>
            <span class="crumbs-spacer"><i class="fa fa-angle-double-right"></i></span>
            <span class="current">Product Details</span>
            <h2 class="entry-title">Details</h2>
          </div>
        </div>
      </div>
    </div>
  </div>


  

{%endblock%}